name: Build Unsigned IPA (TrollStore)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Package IPA
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build Xcode Project
        run: |
          # لێرەدا فەرمانی کۆمپایلکردنەکە دەدرێت بەبێ بڕوانامەی ئەپڵ
          xcodebuild clean build \
            -project "Malimite.xcodeproj" \
            -scheme "Malimite" \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            ENTITLEMENTS_REQUIRED=NO \
            SYMROOT=$PWD/build

      - name: Package into IPA
        run: |
          echo "Packaging the app into an IPA file..."
          mkdir -p Payload
          
          # گواستنەوەی بەرنامەکە بۆ ناو فۆڵدەری پەیلۆد بۆ دروستکردنی فایلی ئای پی ئەی
          mv build/Release-iphoneos/*.app Payload/
          
          # پەستێواندنی فایلەکان
          zip -r Malimite.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Malimite-TrollStore-Build
          path: Malimite.ipa
          retention-days: 7
